### ISSUE TITLE
does it needs his own repo or could we put it here too ?

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/eos-settings-plasma#1]
https://github.com/endeavouros-team/endeavouros-DE-fixes/tree/main/plasma

**Comment by dalto8** [comment]
By putting all the DE stuff in a single repo, we have to clone the entire thing every time we build any part of it.

It probably makes more sense to split them out.

**Comment by killajoe** [comment]
is it a huge problem? As it does include only little code snippets ?

**Comment by dalto8** [comment]
It isn't an enormous problem but shouldn't we try to fix bad practices when we find them?

Combining all that stuff from a bunch of different packages into a single repo isn't ideal.

**Comment by killajoe** [comment]
Even more bad practice is to leave it half-used and unchanged.

**Comment by dalto8** [comment]
True, but we need to start somewhere
