### ISSUE TITLE
Make a colorscheme called EndeavourOS Breeze Dark with purple as the highlight color to be part of the EOS Global Theme

### ISSUE THREAD

**Issue by ghost** [endeavouros-team/eos-settings-plasma#2]
You just have to edit the Breeze Dark colorscheme, select the breeze purple color as the highlight color etc, save it as "EndeavourOS Breeze Dark" and then package the file at `~/.local/share/color-schemes/EndeavourOS Breeze Dark` as part of this package. Currently EOS selects a custom accent color (purple) as the highlight color on the Breeze Dark colorscheme by default. This would actually make this global theme useful as the EOS purple accent color would be part of the EOS global theme's colorscheme.

**Comment by dalto8** [comment]
We already have a custom theme that inherits from Breeze Dark with purple highlights.

It is included in the package `eos-settings-plasma`

**Comment by ghost** [comment]
> We already have a custom theme that inherits from Breeze Dark with purple highlights.
> 
> It is included in the package `eos-settings-plasma`

I have it installed and the global theme set but it uses the breeze dark scheme and the purple highlights come from the custom accent color selection bar like so
![accent selection bar](https://github.com/endeavouros-team/eos-settings-plasma/assets/95931540/df6c94c9-62e3-4ba2-a969-efc679362a00) which applies to all the schemes instead of this one only. What I want you to do is to create a EndeavourOS Breeze Dark scheme like so;



and make it part of the EOS global theme so even when the 'Use accent color from current color scheme' is selected, the global theme could still retain its purple color.

I am sorry if my point didn't get across to you. I have difficulty communicating.

**Comment by dalto8** [comment]
Can you explain how that would be advantageous over the current implementation?

**Comment by ghost** [comment]
> Can you explain how that would be advantageous over the current implementation?

Each colorscheme by default would use its own accent color not the purple. This would make users get the blue highlight with breeze dark colorscheme by default or the default highlight color for their other schemes instead of the purple on all of their schemes by default. This IMO would be much better default.

**Comment by dalto8** [comment]
We didn't do that because we generally wanted to inherit the changes from breeze dark and not maintain an entire theme.

I think the advantage here is not high enough to justify doing that.
